fixing https we currently need to use ALLOW_ALL_HOSTNAME_VERIFIER because otherwise host verification fails with errors like the following:
java.lang.AssertionError: hostname in certificate didn't match: <api.mob1.stackmob.com/72.2.121.229> != <*.mob1.stackmob.com> OR <mob1.stackmob.com> OR <*.mob1.stackmob.com>